[package]
name = "wgpu_test"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "24.0.1"
winit = "0.30.9"
bytemuck = { version = "1.22.0", features = ["derive"] }
pollster = "0.2"
cgmath = "0.18"
image = "0.24"

